# Generated by Django 3.1.6 on 2021-06-14 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='location_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.location_category'),
        ),
    ]
