# Generated by Django 3.1.6 on 2021-06-14 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210614_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiving',
            old_name='delivery_from',
            new_name='delivery_description',
        ),
        migrations.AddField(
            model_name='receiving',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
