# Generated by Django 3.1.6 on 2021-06-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20210615_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='invoice_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='vendor',
            field=models.CharField(max_length=200),
        ),
    ]
