# Generated by Django 3.1.6 on 2021-06-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20210615_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiving_detail',
            old_name='stock_in',
            new_name='receiving',
        ),
        migrations.AddField(
            model_name='receiving_detail',
            name='condition',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
