# Generated by Django 3.1.6 on 2021-06-15 21:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20210615_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Releasing_Detail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.product')),
                ('releasing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.releasing')),
            ],
        ),
    ]
