# Generated by Django 3.1.6 on 2021-06-15 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0009_releasing_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location_category',
        ),
        migrations.AddField(
            model_name='brand',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location_Category',
        ),
    ]
