# Generated by Django 3.1.4 on 2021-06-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_customer_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='datetime',
            new_name='date',
        ),
    ]
