# Generated by Django 3.1.4 on 2021-06-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20210617_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['branch']},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='condition',
            field=models.CharField(choices=[('1', 'Brand New Unit'), ('2', 'Unit Operational'), ('3', 'Unit Standby'), ('4', 'Unit Repair'), ('5', 'Under Observation')], max_length=200),
        ),
    ]
