# Generated by Django 3.1.4 on 2021-06-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('1', 'JPY'), ('2', 'USD'), ('3', 'PESO')], default='1', max_length=200),
        ),
    ]
